### ISSUE TITLE
script 5c return nans...

### ISSUE THREAD

**Issue by rb643** [autism-research-centre/Autism-Gradients#13]
For some strange reason the subsetting at the beginning of 5c return an array of NaN's even though the csv definitely contains normal integers...

**Comment by janfreyberg** [comment]
I think it might have to do with column names being strings not numbers, but I'll take a look tomorrow!

**Comment by janfreyberg** [comment]
works now!

**Comment by rb643** [comment]
As soon as I try to select one column they revert back to NaNs though...

This part: 
ASC = df['DX_GROUP'] == 2
G1 = df[ASC]

Then G1 is again NaNs

**Comment by janfreyberg** [comment]
I think you need to use double-square brackets:

In [6]:
```
# Column names are strings, so need to provide a list of strings to index:
df = output[['DX_GROUP'] + [str(x) for x in range(9)]]

(df[['DX_GROUP']] == 2).head()
```
Out [6]:

Row | DX_GROUP
----|----------
0|False
1|False
2|False
3|False
4|False

**Comment by rb643** [comment]
Ah yes you're right!
