### ISSUE TITLE
Upload raw time series data 

### ISSUE THREAD

**Issue by rb643** [autism-research-centre/Autism-Gradients#9]
Upload raw time series data for the relevant subject to github so people can run everything self-contained from the start.

Also include the phenotype file.

**Comment by janfreyberg** [comment]
Could also just include the download script and a call to it in the main notebook

**Comment by rb643** [comment]
I'll add a Step 0 notebook with that function and the caller in case someone would want to change it, I'm uploading the raw time series to github now in a /data/Inputs folder and changed the gitignore to ignore any output, but at least this way anyone could just download/clone the repository and run through all of the steps. I'm also breaking the main script up in steps see the other thread on that
